verbose: True
dataset: 'tumrgbd'

stride: 1
setting: tum

exposure_compensate: True

mapping:
  BA: False
  mapping_window_size: 5
  iters: 50

final_refine:
  max_steps: 26000
  densify_until_iter: 15000
  densify_from_iter: 300
  densification_interval: 300
  opacity_reset_interval: 3000

tracking:
  buffer: 600
  beta: 0.75
  warmup: 12
  motion_filter:
    thresh: 4.0  
  multiview_filter:
    thresh: 0.03  
    visible_num: 2  
  frontend:
    enable_loop: True
    enable_online_ba: True
    keyframe_thresh: 3.0
    thresh: 16.0
    window: 25
    radius: 2
    nms: 1
  backend:
    final_ba: True
    thresh: 25.0
    radius: 1
    nms: 5
    # used for loop detection
    loop_window: 25
    loop_thresh: 25.0  
    loop_radius: 1
    loop_nms: 10
    BA_type: "DBA"
    normalize: False


cam:  #NOTE: intrinsic is different per scene in TUM
  # refer to https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats#intrinsic_camera_calibration_of_the_kinect
  png_depth_scale: 5000.0 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 8
  W_edge: 8
  H_out: 384
  W_out: 512

mono_prior:
  depth: omnidata
  depth_pretrained: ./pretrained/omnidata_dpt_depth_v2.ckpt
  predict_online: True

data:
  output: output/TUM_RGBD