verbose: True
dataset: 'replica'
stride: 1
setting: replica

deblur: False
use_sensor_depth: False
generate_mesh: True
mapping:
  color_refine: True
  mapping_window_size: 5
  iters: 50

tracking:
  buffer: 400
  beta: 0.6
  warmup: 8
  max_age: 50
  mono_thres: False
  motion_filter:
    thresh: 1.75  
  multiview_filter:
    thresh: 0.01 
    visible_num: 2  
  frontend:
    enable_loop: True
    enable_online_ba: True
    keyframe_thresh: 2.25 
    thresh: 25.0  
    window: 50
    radius: 2
    nms: 1
    max_factors: 100  
  backend:
    # used for loop detection
    ba_freq: 20
    final_ba: True
    loop_window: 25
    loop_nms: 25
    BA_type: "DBA"
    normalize: False

final_refine:
  max_steps: 2000
  densify_until_iter: 1000
  densify_from_iter: 200
  densification_interval: 200
  opacity_reset_interval: 3000

cam:
  ### original camera parameters
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 0
  W_edge: 0
  H_out: 320
  W_out: 640


data:
  output: output/Replica