verbose: True
dataset: ''
setting: ''          # name of the output folder
stride: 1            # use every X image from the dataset 
max_frames: -1       # use the first X images from the dataset, -1 means using all
only_tracking: False # only do tracking without mapping if enabled
setup_seed: 43
wandb: True         # whether to log through wandb
wandb_folder: /wandb/dags/output
device: "cuda"
mode: mono
deblur_idx: ''
use_sensor_depth: False

depth_valid_threshold: 1000
deblur: True
only_deblur_test: False
exposure_compensate: False
map_deformation: True
generate_mesh: False

mapping:
  every_keyframe: 1        # do mapping every X keyframes
  mapping_window_size: 5   # X - 2 keyframes used for mapping. 2X used for color refinement step (if used)
  iters: 50         # how many iterations of optimizer per mapping stage

tracking:
  pretrained: ./pretrained/droid.pth
  buffer: 512     # maximum number of keyframes that can be stored
  beta: 0.75      # beta * Distance(R|t) + (1-beta) * Distance(I|t), refer to droid_kernels.cu:frame_distance_kernel
  warmup: 8       # use the first X keyframes for bootstrapping the tracker
  max_age: 50     # remove edges in the graph if they have been updated more than X times
  mono_thres: 0.1 # in DSPO, remove the edges if the average disp error of the aligned mono disp is larger than X*average_disp
                  # it can be set to False for keeping all edges.
  upsample: True
  motion_filter:
    thresh: 4.0     # add new frame as potential keyframe if avg flow >= X pixels
  multiview_filter:
    thresh: 0.01    #0.01 default    # eta in eq(6) of the paper
    visible_num: 2  # points need to be viewed by at least X cameras
  frontend:
    enable_loop: True      # whether to enable loop closure
    enable_online_ba: True # whether to enable online bundle adjustment
    keyframe_thresh: 4.0   # remove keyframe if it is too close to the last keyframe, i.e. avg flow < X pixels
    thresh: 16.0           # only consider edge with avg flow < X pixels
    window: 25             # local ba window size
    radius: 1              # build edges within local window [i-radius, i]
    nms: 1                 # r_local in GO-SLAM paper
    max_factors: 75        # maximum number of edges in local ba
  backend:
    final_ba: True # whether to enable final global bundle adjustment in the end
    ba_freq: 20    # do online bundle adjustment every X keyframes
    thresh: 25.0   # only consider edge with avg flow < X pixels
    radius: 1      # build edges within local window [i-radius, i]
    nms: 5         # r_global in GO-SLAM paper
    # used for loop detection
    loop_window: 25    # N_local in GO-SLAM paper
    loop_thresh: 25.0  # only consider edge with avg flow < X pixels
    loop_radius: 1     # build edges within local window [i-radius, i]
    loop_nms: 12       # r_loop in GO-SLAM paper
    BA_type: "DBA"    # "DSPO" or "DBA"
    normalize: True    # whether to normalize disps after each BA iter

cam:
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 0
  W_edge: 0
  H_out: 480
  W_out: 640

data:
  input_folder: ''
  output: ''

meshing:
  gt_mesh_path: ''

prior_estimator:
  model: 'yvanyin/metric3d'
  type: 'metric3d_vit_small'
  hubconf_dir: '/root/.cache/torch/hub/yvanyin_metric3d_main'
